services:
  web:
    build:
      context: .
      dockerfile: build/Dockerfile.web
      args:
        - webgraphql=/api
        - auth0client=${POI_APP_DEV_AUTH0_CLIENTID}
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: build/Dockerfile.api
    environment:
      - PROD_API_PORT=4002
      - PROD_DB_NAME=cs
      - PROD_DB_PASSWORD=wat
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=wat
    volumes:
      - /attic/***REMOVED***data/local_content_sieve:/var/lib/postgresql/data
